import { promises as fs } from 'node:fs'
import path from 'node:path'
import {
  DEFAULT_ORIGINAL_SUBTITLE_COLOR,
  DEFAULT_TRANSLATED_SUBTITLE_COLOR,
  hexToAssBgr,
  hexToAssPrimaryColour,
  normalizeHexColor,
} from '../../shared/settings'
import type {
  SubtitleEntry,
  TranscriptionSegment,
} from '../../shared/types/video'
import type { DisplaySegment } from './display-segment-builder'
import { getAsrSourceForArtifacts, getTranslatedText } from './segment-text'
import { SubtitleGenerator } from './subtitle-generator'
import {
  computeSubtitleLayout,
  escapeAssText,
  formatAssTimestamp,
  wrapForDisplay,
  type SubtitleBurnMode,
  type VideoDisplaySize,
} from './subtitle-layout'

/** ASS / 硬字幕颜色（#RRGGBB） */
export interface SubtitleColors {
  originalColor?: string
  translatedColor?: string
}

function resolveSubtitleColors(colors?: SubtitleColors | null): {
  original: string
  translated: string
} {
  return {
    original: normalizeHexColor(
      colors?.originalColor,
      DEFAULT_ORIGINAL_SUBTITLE_COLOR
    ),
    translated: normalizeHexColor(
      colors?.translatedColor,
      DEFAULT_TRANSLATED_SUBTITLE_COLOR
    ),
  }
}

export interface SubtitleArtifactPaths {
  original: string
  translated: string
  bilingual: string
  bilingualAss: string
  outputDirectory: string
}

export interface SubtitleArtifactValidation {
  ok: boolean
  errors: string[]
  checks: {
    originalExists: boolean
    translatedExists: boolean
    bilingualExists: boolean
    bilingualAssExists: boolean
    originalCount: number
    translatedCount: number
    bilingualCount: number
    assDialogueCount: number
    expectedCount: number
    allTranslated: boolean
  }
}

/** 产物「原文」轨：ASR 不可变文本（见 segment-text 策略） */
function displaySourceText(
  segment: DisplaySegment | TranscriptionSegment
): string {
  return getAsrSourceForArtifacts(segment)
}

/** 产物「译文」轨 */
function displayTargetText(
  segment: DisplaySegment | TranscriptionSegment
): string {
  return getTranslatedText(segment)
}

export function segmentsToOriginalSubtitles(
  segments: Array<DisplaySegment | TranscriptionSegment>,
  size?: Partial<VideoDisplaySize> | null
): SubtitleEntry[] {
  const layout = computeSubtitleLayout(size)
  return segments.map((segment, index) => ({
    index: index + 1,
    start: SubtitleGenerator.formatTime(segment.start, 'srt'),
    end: SubtitleGenerator.formatTime(segment.end, 'srt'),
    text: wrapForDisplay(displaySourceText(segment), layout.sourceColumns),
  }))
}

export function segmentsToTranslatedSubtitles(
  segments: Array<DisplaySegment | TranscriptionSegment>,
  size?: Partial<VideoDisplaySize> | null
): SubtitleEntry[] {
  const layout = computeSubtitleLayout(size)
  return segments.map((segment, index) => ({
    index: index + 1,
    start: SubtitleGenerator.formatTime(segment.start, 'srt'),
    end: SubtitleGenerator.formatTime(segment.end, 'srt'),
    text: wrapForDisplay(displayTargetText(segment), layout.targetColumns),
  }))
}

export function segmentsToBilingualSubtitles(
  segments: Array<DisplaySegment | TranscriptionSegment>,
  size?: Partial<VideoDisplaySize> | null
): SubtitleEntry[] {
  const layout = computeSubtitleLayout(size)
  return segments.map((segment, index) => {
    const source = wrapForDisplay(
      displaySourceText(segment),
      layout.sourceColumns
    )
    const target = wrapForDisplay(
      displayTargetText(segment),
      layout.targetColumns
    )
    return {
      index: index + 1,
      start: SubtitleGenerator.formatTime(segment.start, 'srt'),
      end: SubtitleGenerator.formatTime(segment.end, 'srt'),
      text: `${source}\n${target}`,
    }
  })
}

/**
 * 生成底部堆叠双语 ASS：原文在上、译文在下，带半透明底框。
 */
export function generateBilingualAss(
  segments: Array<DisplaySegment | TranscriptionSegment>,
  size?: Partial<VideoDisplaySize> | null,
  font = 'Sans',
  colors?: SubtitleColors | null
): string {
  const layout = computeSubtitleLayout(size)
  const { original, translated } = resolveSubtitleColors(colors)
  const originalAss = hexToAssBgr(original)
  const translatedAss = hexToAssBgr(translated)
  const primaryColour = hexToAssPrimaryColour(original)
  const header = `[Script Info]
; Generated by video-translate bilingual subtitle pipeline
ScriptType: v4.00+
PlayResX: ${layout.playResX}
PlayResY: ${layout.playResY}
WrapStyle: 2
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Bilingual,${font},${layout.targetFontSize},${primaryColour},&H000000FF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,1,2,${layout.marginX},${layout.marginX},${layout.bottomMargin},1
Style: BilingualBox,${font},${layout.targetFontSize},&HFF000000,&HFF000000,&H78000000,&H78000000,-1,0,0,0,100,100,0,0,4,8,0,2,${layout.marginX},${layout.marginX},${layout.bottomMargin},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`

  const dialogue = segments.map(segment => {
    const source = wrapForDisplay(
      displaySourceText(segment),
      layout.sourceColumns
    )
    const target = wrapForDisplay(
      displayTargetText(segment),
      layout.targetColumns
    )
    const escapedSource = escapeAssText(source)
    const escapedTarget = escapeAssText(target)
    const start = formatAssTimestamp(segment.start)
    const end = formatAssTimestamp(
      Math.max(segment.end, segment.start + 0.01),
      true
    )
    const anchor = `{\\an2\\pos(${layout.positionX},${layout.positionY})\\fs${layout.sourceFontSize}}`
    const boxText = `${anchor}${escapedSource}\\N{\\fs${layout.targetFontSize}}${escapedTarget}`
    const text = `${anchor}{\\1c${originalAss}}${escapedSource}\\N{\\fs${layout.targetFontSize}\\1c${translatedAss}}${escapedTarget}`
    return [
      `Dialogue: 0,${start},${end},BilingualBox,,0,0,0,,${boxText}`,
      `Dialogue: 1,${start},${end},Bilingual,,0,0,0,,${text}`,
    ].join('\n')
  })

  return `${header}${dialogue.join('\n')}\n`
}

/**
 * 单语 ASS（译文或原文），仍使用布局换行与底部安全区。
 */
export function generateMonolingualAss(
  segments: Array<DisplaySegment | TranscriptionSegment>,
  mode: 'translated' | 'original',
  size?: Partial<VideoDisplaySize> | null,
  font = 'Sans',
  colors?: SubtitleColors | null
): string {
  const layout = computeSubtitleLayout(size)
  const resolved = resolveSubtitleColors(colors)
  const hex = mode === 'original' ? resolved.original : resolved.translated
  const primaryColour = hexToAssPrimaryColour(hex)
  const inlineColour = hexToAssBgr(hex)
  const header = `[Script Info]
ScriptType: v4.00+
PlayResX: ${layout.playResX}
PlayResY: ${layout.playResY}
WrapStyle: 2
ScaledBorderAndShadow: yes

[V4+ Styles]
Format: Name, Fontname, Fontsize, PrimaryColour, SecondaryColour, OutlineColour, BackColour, Bold, Italic, Underline, StrikeOut, ScaleX, ScaleY, Spacing, Angle, BorderStyle, Outline, Shadow, Alignment, MarginL, MarginR, MarginV, Encoding
Style: Main,${font},${layout.targetFontSize},${primaryColour},&H000000FF,&H00000000,&H64000000,-1,0,0,0,100,100,0,0,1,2,1,2,${layout.marginX},${layout.marginX},${layout.bottomMargin},1

[Events]
Format: Layer, Start, End, Style, Name, MarginL, MarginR, MarginV, Effect, Text
`

  const dialogue = segments.map(segment => {
    const raw =
      mode === 'original'
        ? displaySourceText(segment)
        : displayTargetText(segment)
    const text = wrapForDisplay(
      raw,
      mode === 'original' ? layout.sourceColumns : layout.targetColumns
    )
    const start = formatAssTimestamp(segment.start)
    const end = formatAssTimestamp(
      Math.max(segment.end, segment.start + 0.01),
      true
    )
    const body = `{\\an2\\pos(${layout.positionX},${layout.positionY})\\1c${inlineColour}}${escapeAssText(text)}`
    return `Dialogue: 0,${start},${end},Main,,0,0,0,,${body}`
  })

  return `${header}${dialogue.join('\n')}\n`
}

export function selectBurnSubtitleContent(
  mode: SubtitleBurnMode,
  segments: Array<DisplaySegment | TranscriptionSegment>,
  size?: Partial<VideoDisplaySize> | null,
  colors?: SubtitleColors | null
): { extension: 'ass'; content: string } {
  if (mode === 'bilingual') {
    return {
      extension: 'ass',
      content: generateBilingualAss(segments, size, 'Sans', colors),
    }
  }
  if (mode === 'original') {
    return {
      extension: 'ass',
      content: generateMonolingualAss(
        segments,
        'original',
        size,
        'Sans',
        colors
      ),
    }
  }
  return {
    extension: 'ass',
    content: generateMonolingualAss(
      segments,
      'translated',
      size,
      'Sans',
      colors
    ),
  }
}

function buildArtifactPaths(
  outputDir: string,
  baseName: string,
  sourceSuffix: string,
  targetSuffix: string,
  sequence: number
): SubtitleArtifactPaths {
  const version = sequence === 1 ? '' : `.${sequence}`
  return {
    original: path.join(outputDir, `${baseName}_${sourceSuffix}${version}.srt`),
    translated: path.join(
      outputDir,
      `${baseName}_${targetSuffix}${version}.srt`
    ),
    bilingual: path.join(outputDir, `${baseName}_bilingual${version}.srt`),
    bilingualAss: path.join(outputDir, `${baseName}_bilingual${version}.ass`),
    outputDirectory: outputDir,
  }
}

async function removeReservedFiles(paths: string[]): Promise<void> {
  const results = await Promise.allSettled(
    paths.map(filePath => fs.unlink(filePath))
  )
  const failure = results.find(
    result =>
      result.status === 'rejected' &&
      (!result.reason ||
        typeof result.reason !== 'object' ||
        !('code' in result.reason) ||
        result.reason.code !== 'ENOENT')
  )
  if (failure?.status === 'rejected') {
    throw failure.reason
  }
}

/** 排他预占整组产物，冲突时整组递增编号。 */
async function reserveArtifactPaths(
  outputDir: string,
  baseName: string,
  sourceSuffix: string,
  targetSuffix: string
): Promise<SubtitleArtifactPaths> {
  for (let sequence = 1; ; sequence += 1) {
    const paths = buildArtifactPaths(
      outputDir,
      baseName,
      sourceSuffix,
      targetSuffix,
      sequence
    )
    const files = [
      paths.original,
      paths.translated,
      paths.bilingual,
      paths.bilingualAss,
    ]
    if (new Set(files).size !== files.length) {
      throw new Error('字幕原文与译文文件名冲突，请使用不同语言后缀')
    }

    const reserved: string[] = []
    try {
      for (const filePath of files) {
        const handle = await fs.open(filePath, 'wx')
        await handle.close()
        reserved.push(filePath)
      }
      return paths
    } catch (error) {
      await removeReservedFiles(reserved)
      if (
        error &&
        typeof error === 'object' &&
        'code' in error &&
        error.code === 'EEXIST'
      ) {
        continue
      }
      throw error
    }
  }
}

/** 仅生成原文 SRT；同名时递增编号，避免覆盖已有文件。 */
export async function writeOriginalSubtitleArtifact(options: {
  segments: Array<DisplaySegment | TranscriptionSegment>
  outputDir: string
  baseName: string
  sourceSuffix: string
  videoSize?: Partial<VideoDisplaySize> | null
}): Promise<{ original: string; outputDirectory: string }> {
  const { segments, outputDir, baseName, sourceSuffix, videoSize } = options
  await fs.mkdir(outputDir, { recursive: true })

  for (let sequence = 1; ; sequence += 1) {
    const version = sequence === 1 ? '' : `.${sequence}`
    const original = path.join(
      outputDir,
      `${baseName}_${sourceSuffix}${version}.srt`
    )
    let reserved = false
    try {
      const handle = await fs.open(original, 'wx')
      reserved = true
      await handle.close()
      const subtitles = segmentsToOriginalSubtitles(segments, videoSize)
      await SubtitleGenerator.saveSubtitle(subtitles, original, 'srt')
      return { original, outputDirectory: outputDir }
    } catch (error) {
      if (
        !reserved &&
        error &&
        typeof error === 'object' &&
        'code' in error &&
        error.code === 'EEXIST'
      ) {
        continue
      }
      if (reserved) {
        await removeReservedFiles([original])
      }
      throw error
    }
  }
}

export async function writeSubtitleArtifacts(options: {
  segments: Array<DisplaySegment | TranscriptionSegment>
  outputDir: string
  baseName: string
  sourceSuffix: string
  targetSuffix: string
  videoSize?: Partial<VideoDisplaySize> | null
  colors?: SubtitleColors | null
}): Promise<SubtitleArtifactPaths> {
  const {
    segments,
    outputDir,
    baseName,
    sourceSuffix,
    targetSuffix,
    videoSize,
    colors,
  } = options

  await fs.mkdir(outputDir, { recursive: true })

  const paths = await reserveArtifactPaths(
    outputDir,
    baseName,
    sourceSuffix,
    targetSuffix
  )

  const original = segmentsToOriginalSubtitles(segments, videoSize)
  const translated = segmentsToTranslatedSubtitles(segments, videoSize)
  const bilingual = segmentsToBilingualSubtitles(segments, videoSize)
  const ass = generateBilingualAss(segments, videoSize, 'Sans', colors)

  try {
    await SubtitleGenerator.saveSubtitle(original, paths.original, 'srt')
    await SubtitleGenerator.saveSubtitle(translated, paths.translated, 'srt')
    await SubtitleGenerator.saveSubtitle(bilingual, paths.bilingual, 'srt')
    await fs.writeFile(paths.bilingualAss, ass, 'utf-8')
    return paths
  } catch (error) {
    await removeReservedFiles([
      paths.original,
      paths.translated,
      paths.bilingual,
      paths.bilingualAss,
    ])
    throw error
  }
}

async function fileNonEmpty(filePath: string): Promise<boolean> {
  try {
    const stat = await fs.stat(filePath)
    return stat.isFile() && stat.size > 0
  } catch {
    return false
  }
}

function countSrtCues(content: string): number {
  const blocks = content
    .trim()
    .split(/\n\s*\n/)
    .filter(block => /^\d+\s*$/m.test(block.split('\n')[0] ?? ''))
  return blocks.length
}

/**
 * 产物完整性校验：文件存在、非空、条数一致、译文齐全。
 */
export async function validateSubtitleArtifacts(
  paths: SubtitleArtifactPaths,
  segments: Array<DisplaySegment | TranscriptionSegment>
): Promise<SubtitleArtifactValidation> {
  const errors: string[] = []
  const expectedCount = segments.length

  const [
    originalExists,
    translatedExists,
    bilingualExists,
    bilingualAssExists,
  ] = await Promise.all([
    fileNonEmpty(paths.original),
    fileNonEmpty(paths.translated),
    fileNonEmpty(paths.bilingual),
    fileNonEmpty(paths.bilingualAss),
  ])

  if (!originalExists) errors.push(`原文字幕缺失或为空: ${paths.original}`)
  if (!translatedExists) errors.push(`译文字幕缺失或为空: ${paths.translated}`)
  if (!bilingualExists) errors.push(`双语字幕缺失或为空: ${paths.bilingual}`)
  if (!bilingualAssExists)
    errors.push(`双语 ASS 缺失或为空: ${paths.bilingualAss}`)

  let originalCount = 0
  let translatedCount = 0
  let bilingualCount = 0
  let assDialogueCount = 0

  if (originalExists) {
    const content = await fs.readFile(paths.original, 'utf-8')
    originalCount = countSrtCues(content)
    if (originalCount !== expectedCount) {
      errors.push(
        `原文字幕条数不一致: 期望 ${expectedCount}，实际 ${originalCount}`
      )
    }
  }

  if (translatedExists) {
    const content = await fs.readFile(paths.translated, 'utf-8')
    translatedCount = countSrtCues(content)
    if (translatedCount !== expectedCount) {
      errors.push(
        `译文字幕条数不一致: 期望 ${expectedCount}，实际 ${translatedCount}`
      )
    }
  }

  if (bilingualExists) {
    const content = await fs.readFile(paths.bilingual, 'utf-8')
    bilingualCount = countSrtCues(content)
    if (bilingualCount !== expectedCount) {
      errors.push(
        `双语字幕条数不一致: 期望 ${expectedCount}，实际 ${bilingualCount}`
      )
    }
  }

  if (bilingualAssExists) {
    const content = await fs.readFile(paths.bilingualAss, 'utf-8')
    assDialogueCount = content.match(/^Dialogue:/gm)?.length ?? 0
    const expectedDialogueCount = expectedCount * 2
    if (assDialogueCount !== expectedDialogueCount) {
      errors.push(
        `ASS 事件数不一致: 期望 ${expectedDialogueCount}，实际 ${assDialogueCount}`
      )
    }
  }

  const allTranslated = segments.every(segment => {
    const text = (segment.translatedText || '').trim()
    return text.length > 0
  })
  if (expectedCount > 0 && !allTranslated) {
    errors.push('存在未翻译段落')
  }

  if (expectedCount === 0) {
    errors.push('没有可用于输出的字幕段落')
  }

  return {
    ok: errors.length === 0,
    errors,
    checks: {
      originalExists,
      translatedExists,
      bilingualExists,
      bilingualAssExists,
      originalCount,
      translatedCount,
      bilingualCount,
      assDialogueCount,
      expectedCount,
      allTranslated,
    },
  }
}
